name: Deploy static HTML site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './' # Adjust this to the path of your static site files if needed

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
=======
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./your-site-directory  # Replace with your actual site directory
>>>>>>> 47bb758e3d0bfa58918646f2ef20e05251230137
