name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: actions/setup-pages@v3

    - name: Push to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p out
        cp -r * out
        touch out/.nojekyll
        echo "<meta http-equiv='refresh' content='0; url=/your-site/' />" > out/index.html
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

        git init
        git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
        git fetch
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        cp -r out/* .
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages
