name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload HTML files to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'   # Adjust this according to your HTML structure

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1