name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GitHub Pages
      uses: actions/setup-pages@v1

    - name: Deploy to GitHub Pages
      run: |-
        mkdir -p out
        cp -r * out/
        echo "html" > out/.nojekyll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: out

    - name: Commit GitHub Pages
      uses: actions/deploy-pages@v1
