```yaml
name: Deploy Static HTML Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 12 * * *'  # 6 PM IST is 12:30 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/setup-pages@v2

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
```