name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        folder: '.'  # Specify the folder to deploy, usually it's the root for a static site